CREATE TABLE USER(ID VARCHAR(20) PRIMARY KEY, USER_NAME VARCHAR(255), EMAIL_ID VARCHAR(255), PASSWORD VARCHAR(10) NOT NULL, IMAGE BLOB );

create sequence UserOtpIdSequence;
CREATE TABLE USER_OTP(ID bigint default UserOtpIdSequence.nextval  primary key, USER_ID VARCHAR(20) , OTP  VARCHAR(8) , OTP_GENERATED_TMSTMP TIMESTAMP, FOREIGN KEY(USER_ID) REFERENCES USER(ID));

CREATE TABLE STATE(STATE_ID INT PRIMARY KEY, STATE_NAME VARCHAR(255));

CREATE TABLE ADDRESS(ADDRESS_ID VARCHAR(20) PRIMARY KEY, HOUSE_NO INT, STREET VARCHAR(255), CITY VARCHAR(255), STATE_ID INT, COUNTRY VARCHAR(10),
FOREIGN KEY(ADDRESS_ID) REFERENCES USER(ID),
FOREIGN KEY(STATE_ID) REFERENCES STATE(STATE_ID)
);



INSERT INTO STATE VALUES(1, 'Delhi');
INSERT INTO STATE VALUES(2, 'Maharashtra');
INSERT INTO STATE VALUES(3, 'Andhra Pradesh');
INSERT INTO STATE VALUES(4, 'Madhya Pradesh');
INSERT INTO STATE VALUES(5, 'Uttar Pradesh');
INSERT INTO STATE VALUES(6, 'Gujrat');
INSERT INTO STATE VALUES(7, 'Rajasthan');
INSERT INTO STATE VALUES(8, 'Punjab');
INSERT INTO STATE VALUES(9, 'Jammu and Kashmir');
